-- MySQL Script generated by MySQL Workbench
-- 08/11/14 22:17:43
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`ComprobantesContables`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ComprobantesContables` (
  `idComprobante` INT NOT NULL,
  `Fecha` DATE NULL,
  `Numero` INT NULL,
  `Debe` VARCHAR(45) NULL,
  `Haber` VARCHAR(45) NULL,
  `Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idComprobante`),
  INDEX `fk_ComprobantesContables_Cliente1_idx` (`Cliente_idCliente` ASC),
  CONSTRAINT `fk_ComprobantesContables_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CuentasContables`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CuentasContables` (
  `idCuentas` INT NOT NULL,
  `Codigo` VARCHAR(45) NULL,
  `Nombre` VARCHAR(45) NULL,
  `ComprobantesContables_idComprobante` INT NOT NULL,
  PRIMARY KEY (`idCuentas`),
  INDEX `fk_CuentasContables_ComprobantesContables1_idx` (`ComprobantesContables_idComprobante` ASC),
  CONSTRAINT `fk_CuentasContables_ComprobantesContables1`
    FOREIGN KEY (`ComprobantesContables_idComprobante`)
    REFERENCES `mydb`.`ComprobantesContables` (`idComprobante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `idCliente` INT NOT NULL,
  `RazonSocial` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `CuentasContables_idCuentas` INT NOT NULL,
  PRIMARY KEY (`idCliente`),
  INDEX `fk_Cliente_CuentasContables1_idx` (`CuentasContables_idCuentas` ASC),
  CONSTRAINT `fk_Cliente_CuentasContables1`
    FOREIGN KEY (`CuentasContables_idCuentas`)
    REFERENCES `mydb`.`CuentasContables` (`idCuentas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`GrupoTrabajo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`GrupoTrabajo` (
  `idGrupo` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idGrupo`),
  INDEX `fk_GrupoTrabajo_Cliente1_idx` (`Cliente_idCliente` ASC),
  CONSTRAINT `fk_GrupoTrabajo_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Parametros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Parametros` (
  `idParametros` INT NOT NULL,
  `Tipo` VARCHAR(45) NULL,
  `Nombre` VARCHAR(45) NULL,
  `Valor` VARCHAR(45) NULL,
  `Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idParametros`),
  INDEX `fk_Parametros_Cliente1_idx` (`Cliente_idCliente` ASC),
  CONSTRAINT `fk_Parametros_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empleados` (
  `idEmpleado` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Apellido` VARCHAR(45) NULL,
  `ApCasada` VARCHAR(45) NULL,
  `Rol` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idEmpleado`),
  INDEX `fk_Empleados_Cliente1_idx` (`Cliente_idCliente` ASC),
  CONSTRAINT `fk_Empleados_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuarios` (
  `idUsuario` INT NOT NULL,
  `Tipo` VARCHAR(45) NULL,
  `Nombre` VARCHAR(45) NULL,
  `Apellido` VARCHAR(45) NULL,
  `ApCasada` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_Usuarios_Cliente1_idx` (`Cliente_idCliente` ASC),
  CONSTRAINT `fk_Usuarios_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Remuneraciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Remuneraciones` (
  `idRemuneracion` INT NOT NULL,
  `DiasTrabajados` VARCHAR(45) NULL,
  `Mes` VARCHAR(45) NULL,
  `Año` VARCHAR(45) NULL,
  `Empleados_idEmpleado` INT NOT NULL,
  PRIMARY KEY (`idRemuneracion`),
  INDEX `fk_Remuneraciones_Empleados1_idx` (`Empleados_idEmpleado` ASC),
  CONSTRAINT `fk_Remuneraciones_Empleados1`
    FOREIGN KEY (`Empleados_idEmpleado`)
    REFERENCES `mydb`.`Empleados` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Descuentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Descuentos` (
  `idDescuento` INT NOT NULL,
  `Tipo` VARCHAR(45) NULL,
  `Monto` VARCHAR(45) NULL,
  `Remuneraciones_idRemuneracion` INT NOT NULL,
  PRIMARY KEY (`idDescuento`),
  INDEX `fk_Descuentos_Remuneraciones1_idx` (`Remuneraciones_idRemuneracion` ASC),
  CONSTRAINT `fk_Descuentos_Remuneraciones1`
    FOREIGN KEY (`Remuneraciones_idRemuneracion`)
    REFERENCES `mydb`.`Remuneraciones` (`idRemuneracion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Haberes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Haberes` (
  `idHaber` INT NOT NULL,
  `Tipo` VARCHAR(45) NULL,
  `Monto` VARCHAR(45) NULL,
  `Descripcion` VARCHAR(45) NULL,
  `Remuneraciones_idRemuneracion` INT NOT NULL,
  PRIMARY KEY (`idHaber`),
  INDEX `fk_Haberes_Remuneraciones1_idx` (`Remuneraciones_idRemuneracion` ASC),
  CONSTRAINT `fk_Haberes_Remuneraciones1`
    FOREIGN KEY (`Remuneraciones_idRemuneracion`)
    REFERENCES `mydb`.`Remuneraciones` (`idRemuneracion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
