-- MySQL Script generated by MySQL Workbench
-- 08/09/14 00:25:54
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Sucursal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sucursal` (
  `idSucursal` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Direccion` VARCHAR(45) NULL,
  `Administrador` VARCHAR(45) NULL,
  PRIMARY KEY (`idSucursal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Proveedor` (
  `idProveedor` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Direccion` VARCHAR(45) NULL,
  `Ciudad` VARCHAR(45) NULL,
  `Telefono` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `Nit` VARCHAR(45) NULL,
  PRIMARY KEY (`idProveedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sucursal_Prov`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sucursal_Prov` (
  `Sucursal_idSucursal` INT NOT NULL,
  `Proveedor_idProveedor` INT NOT NULL,
  INDEX `fk_Sucursal_Prov_Sucursal1_idx` (`Sucursal_idSucursal` ASC),
  INDEX `fk_Sucursal_Prov_Proveedor1_idx` (`Proveedor_idProveedor` ASC),
  CONSTRAINT `fk_Sucursal_Prov_Sucursal1`
    FOREIGN KEY (`Sucursal_idSucursal`)
    REFERENCES `mydb`.`Sucursal` (`idSucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sucursal_Prov_Proveedor1`
    FOREIGN KEY (`Proveedor_idProveedor`)
    REFERENCES `mydb`.`Proveedor` (`idProveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `idCliente` INT NOT NULL,
  `Nom` VARCHAR(45) NULL,
  `Ap` VARCHAR(45) NULL,
  `ApCasada` VARCHAR(45) NULL,
  `Telefono` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `Nacionalidad` VARCHAR(45) NULL,
  `dpi` VARCHAR(45) NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tipo_Hab`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tipo_Hab` (
  `idTipo_Hab` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Descripcion` VARCHAR(45) NULL,
  `Capacidad` VARCHAR(45) NULL,
  `Precio` DECIMAL(10,0) NULL,
  PRIMARY KEY (`idTipo_Hab`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Habitacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Habitacion` (
  `idHabitacion` INT NOT NULL,
  `Numero` VARCHAR(45) NULL,
  `Estado` VARCHAR(45) NULL,
  `Sucursal_idSucursal` INT NOT NULL,
  `Tipo_Hab_idTipo_Hab` INT NOT NULL,
  PRIMARY KEY (`idHabitacion`),
  INDEX `fk_Habitacion_Sucursal1_idx` (`Sucursal_idSucursal` ASC),
  INDEX `fk_Habitacion_Tipo_Hab1_idx` (`Tipo_Hab_idTipo_Hab` ASC),
  CONSTRAINT `fk_Habitacion_Sucursal1`
    FOREIGN KEY (`Sucursal_idSucursal`)
    REFERENCES `mydb`.`Sucursal` (`idSucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Habitacion_Tipo_Hab1`
    FOREIGN KEY (`Tipo_Hab_idTipo_Hab`)
    REFERENCES `mydb`.`Tipo_Hab` (`idTipo_Hab`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Acreedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Acreedores` (
  `idAcreedores` INT NOT NULL,
  PRIMARY KEY (`idAcreedores`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sucursal_Acree`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sucursal_Acree` (
  `Sucursal_idSucursal` INT NOT NULL,
  `Acreedores_idAcreedores` INT NOT NULL,
  INDEX `fk_Sucursal_Acree_Sucursal_idx` (`Sucursal_idSucursal` ASC),
  INDEX `fk_Sucursal_Acree_Acreedores1_idx` (`Acreedores_idAcreedores` ASC),
  CONSTRAINT `fk_Sucursal_Acree_Sucursal`
    FOREIGN KEY (`Sucursal_idSucursal`)
    REFERENCES `mydb`.`Sucursal` (`idSucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sucursal_Acree_Acreedores1`
    FOREIGN KEY (`Acreedores_idAcreedores`)
    REFERENCES `mydb`.`Acreedores` (`idAcreedores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Compras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Compras` (
  `idCompras` INT NOT NULL,
  `Proveedor_idProveedor` INT NOT NULL,
  PRIMARY KEY (`idCompras`),
  INDEX `fk_Compras_Proveedor1_idx` (`Proveedor_idProveedor` ASC),
  CONSTRAINT `fk_Compras_Proveedor1`
    FOREIGN KEY (`Proveedor_idProveedor`)
    REFERENCES `mydb`.`Proveedor` (`idProveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Producto` (
  `idProducto` INT NOT NULL,
  `Tipo` VARCHAR(45) NULL,
  `Descripcion` VARCHAR(45) NULL,
  `CantidadTotal` DECIMAL(10,0) NULL,
  `Reorden` DECIMAL(10,0) NULL,
  PRIMARY KEY (`idProducto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Det_Compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Det_Compra` (
  `Cantidad` DECIMAL(10,0) NULL,
  `PrecioTotal` DECIMAL(10,0) NULL,
  `Compras_idCompras` INT NOT NULL,
  `Producto_idProducto` INT NOT NULL,
  INDEX `fk_Det_Compra_Compras1_idx` (`Compras_idCompras` ASC),
  INDEX `fk_Det_Compra_Producto1_idx` (`Producto_idProducto` ASC),
  CONSTRAINT `fk_Det_Compra_Compras1`
    FOREIGN KEY (`Compras_idCompras`)
    REFERENCES `mydb`.`Compras` (`idCompras`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Det_Compra_Producto1`
    FOREIGN KEY (`Producto_idProducto`)
    REFERENCES `mydb`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empleado` (
  `idEmpleado` INT NOT NULL,
  `Nom` VARCHAR(45) NULL,
  `Ap` VARCHAR(45) NULL,
  `ApCasada` VARCHAR(45) NULL,
  `Direccion` VARCHAR(45) NULL,
  `Telefono` VARCHAR(45) NULL,
  `Cargo` VARCHAR(45) NULL,
  `dpi` VARCHAR(45) NULL,
  PRIMARY KEY (`idEmpleado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reservacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Reservacion` (
  `idReservacion` INT NOT NULL,
  `FechaInicio` DATE NULL,
  `FechaFin` DATE NULL,
  `Precio` DECIMAL(10,0) NULL,
  `Ocupacion` VARCHAR(45) NULL,
  `Habitacion_idHabitacion` INT NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  `Empleado_idEmpleado` INT NOT NULL,
  PRIMARY KEY (`idReservacion`),
  INDEX `fk_Reservacion_Habitacion1_idx` (`Habitacion_idHabitacion` ASC),
  INDEX `fk_Reservacion_Cliente1_idx` (`Cliente_idCliente` ASC),
  INDEX `fk_Reservacion_Empleado1_idx` (`Empleado_idEmpleado` ASC),
  CONSTRAINT `fk_Reservacion_Habitacion1`
    FOREIGN KEY (`Habitacion_idHabitacion`)
    REFERENCES `mydb`.`Habitacion` (`idHabitacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reservacion_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reservacion_Empleado1`
    FOREIGN KEY (`Empleado_idEmpleado`)
    REFERENCES `mydb`.`Empleado` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Det_Servicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Det_Servicio` (
  `Descripcion` VARCHAR(45) NULL,
  `Total` DECIMAL(10,0) NULL,
  `Reservacion_idReservacion` INT NOT NULL,
  `Producto_idProducto` INT NOT NULL,
  INDEX `fk_Det_Servicio_Reservacion1_idx` (`Reservacion_idReservacion` ASC),
  INDEX `fk_Det_Servicio_Producto1_idx` (`Producto_idProducto` ASC),
  CONSTRAINT `fk_Det_Servicio_Reservacion1`
    FOREIGN KEY (`Reservacion_idReservacion`)
    REFERENCES `mydb`.`Reservacion` (`idReservacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Det_Servicio_Producto1`
    FOREIGN KEY (`Producto_idProducto`)
    REFERENCES `mydb`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Acreedor_Fact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Acreedor_Fact` (
  `Acreedores_idAcreedores` INT NOT NULL,
  INDEX `fk_Acreedor_Fact_Acreedores1_idx` (`Acreedores_idAcreedores` ASC),
  CONSTRAINT `fk_Acreedor_Fact_Acreedores1`
    FOREIGN KEY (`Acreedores_idAcreedores`)
    REFERENCES `mydb`.`Acreedores` (`idAcreedores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Factura` (
  `No_Factura` INT NOT NULL,
  `Fecha` DATE NULL,
  `Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`No_Factura`),
  INDEX `fk_Factura_Cliente1_idx` (`Cliente_idCliente` ASC),
  CONSTRAINT `fk_Factura_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Det_Factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Det_Factura` (
  `PrecioTotal` DECIMAL(10,0) NULL,
  `Cantidad` DECIMAL(10,0) NULL,
  `Factura_No_Factura` INT NOT NULL,
  `Producto_idProducto` INT NOT NULL,
  `Reservacion_idReservacion` INT NOT NULL,
  INDEX `fk_Det_Factura_Factura1_idx` (`Factura_No_Factura` ASC),
  INDEX `fk_Det_Factura_Producto1_idx` (`Producto_idProducto` ASC),
  INDEX `fk_Det_Factura_Reservacion1_idx` (`Reservacion_idReservacion` ASC),
  CONSTRAINT `fk_Det_Factura_Factura1`
    FOREIGN KEY (`Factura_No_Factura`)
    REFERENCES `mydb`.`Factura` (`No_Factura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Det_Factura_Producto1`
    FOREIGN KEY (`Producto_idProducto`)
    REFERENCES `mydb`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Det_Factura_Reservacion1`
    FOREIGN KEY (`Reservacion_idReservacion`)
    REFERENCES `mydb`.`Reservacion` (`idReservacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Banco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Banco` (
  `idBanco` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Descripcion` VARCHAR(45) NULL,
  `Factura_No_Factura` INT NOT NULL,
  PRIMARY KEY (`idBanco`),
  INDEX `fk_Banco_Factura1_idx` (`Factura_No_Factura` ASC),
  CONSTRAINT `fk_Banco_Factura1`
    FOREIGN KEY (`Factura_No_Factura`)
    REFERENCES `mydb`.`Factura` (`No_Factura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cta_Bancaria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cta_Bancaria` (
  `idCta_Bancaria` INT NOT NULL,
  `Descripcion` VARCHAR(45) NULL,
  `Banco_idBanco` INT NOT NULL,
  PRIMARY KEY (`idCta_Bancaria`),
  INDEX `fk_Cta_Bancaria_Banco1_idx` (`Banco_idBanco` ASC),
  CONSTRAINT `fk_Cta_Bancaria_Banco1`
    FOREIGN KEY (`Banco_idBanco`)
    REFERENCES `mydb`.`Banco` (`idBanco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
